In [1]:
from sklearn.mixture import GaussianMixture
import numpy as np

In [2]:
# Sample data generation
np.random.seed(0)
# Generate random data with two clusters
cluster1 = np.random.normal(loc=0, scale=1, size=(100, 2))
cluster2 = np.random.normal(loc=4, scale=1, size=(100, 2))
data = np.vstack((cluster1, cluster2))

In [3]:
# Fit a Gaussian Mixture Model
gmm = GaussianMixture(n_components=2, random_state=0)
gmm.fit(data)

GaussianMixture(n_components=2, random_state=0)

In [4]:
# Predict the labels
labels = gmm.predict(data)

In [5]:
# Print the means and covariances of each component
print("Means:\n", gmm.means_)
print("Covariances:\n", gmm.covariances_)

Means:
 [[ 3.85370362e+00  3.88214962e+00]
 [-3.65295543e-03  1.41944691e-01]]
Covariances:
 [[[ 0.9340381  -0.06855897]
  [-0.06855897  0.86215101]]

 [[ 1.0412044  -0.02588042]
  [-0.02588042  1.03560327]]]
